import { icons } from "./icons"

export const friends = 
[
    {
        nickName : 'Buttowski',
        icon : icons.users.buttowski,
        isPlaying : true,
        playingFor : 'Spacewar',
        subGame : false,
        id : 1,
        isOnline: true,
        link : 'https://steamcommunity.com/id/PPaNK/',
    },
    {
        nickName : 'Gutsy Heart',
        icon : icons.users.gutsyheart,
        isPlaying : true,
        playingFor : 'Counter Strike',
        subGame : 'Casual - Italy [3:0]',
        id : 2,
        isOnline: true,
        link : 'https://steamcommunity.com/profiles/76561199120581566/',
    },
    {
        nickName : 'ItsLeGeNDaryX',
        icon : icons.users.legendary,
        isPlaying : true,
        playingFor : 'The Long Dark',
        subGame : 'игра в режиме WINTERMUTE',
        id : 3,
        isOnline: true,
        link : 'https://steamcommunity.com/profiles/76561198227643584/',
    },
    {
        nickName : '𝙿𝚑𝚊𝚗𝚝𝚘𝚖',
        icon : icons.users.phantom,
        isPlaying : true,
        playingFor : 'Call of Duty®',
        subGame : false,
        id : 4,
        isOnline: true,
        link : 'https://steamcommunity.com/profiles/76561198370832173/',
    },
    {
        nickName : 'I_Amigo_I',
        icon : icons.users.amigo,
        isPlaying : false,
        playingFor : false,
        subGame : false,
        id : 5,
        isOnline: true,
        link : 'https://steamcommunity.com/profiles/76561198801066209/',
    },
    {
        nickName : 'Sebi',
        icon : icons.users.sebi,
        isPlaying : false,
        playingFor : false,
        subGame : false,
        id : 6,
        isOnline: true,
        link : 'https://steamcommunity.com/profiles/76561198812527343/',
    },
    {
        nickName : 'samad',
        icon : icons.users.samad,
        isPlaying : false,
        playingFor : false,
        subGame : false,
        id : 7,
        isOnline: true,
        link : 'https://steamcommunity.com/id/imsamad/',
    },
    {
        nickName : 'Rengrandt',
        icon : icons.users.reng,
        isPlaying : true,
        playingFor : 'Marvel Rivals',
        subGame : false,
        id : 8,
        isOnline: true,
        link : 'https://steamcommunity.com/profiles/76561199218512587/',
    },
    {
        nickName : 'Dimeni',
        icon : icons.users.dimeni,
        isPlaying : false,
        playingFor : false,
        subGame : false,
        id : 9,
        isOnline: false,
        link : 'https://steamcommunity.com/profiles/76561199795256020/',
    },
    {
        nickName : '_lublu_kvas_',
        icon : icons.users.dimeni,
        isPlaying : false,
        playingFor : false,
        subGame : false,
        id : 10,
        isOnline: false,
        link : 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    },
    {
        nickName : 'Marchy',
        icon : icons.users.marchy,
        isPlaying : false,
        playingFor : false,
        subGame : false,
        id : 11,
        isOnline: false,
        link : 'https://steamcommunity.com/profiles/76561198945173976/',
    },
    {
        nickName : 'СКУФАРЬ',
        icon : icons.users.skuf,
        isPlaying : false,
        playingFor : false,
        subGame : false,
        id : 12,
        isOnline: false,
        link : 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    },
]